# Generated by Django 4.2.4 on 2023-09-01 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
                ('shipper', models.CharField(max_length=200)),
                ('website', models.URLField()),
            ],
        ),
    ]
